services:
  stroy_api:
    build: .
    container_name: stroy_api
    restart: always
    ports:
      - "8888:8080"
    env_file:
      - .env
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8080
      --proxy-headers
      --forwarded-allow-ips="*"
    volumes:
      - .:/app
    depends_on:
      - redis

  postgres:
    image: ankane/pgvector:latest
    container_name: pg_stroy
    restart: always
    ports:
      - "5444:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_stroy
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
